shorty/urls.py
# -*- coding: utf-8 -*-
#    This file is part of Shorty.
#
#    Shorty is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Shorty is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.

from flask.ext.login import login_required

#from shorty.views.frontend import frontend, IndexView, ShortLinkRedirectView
from shorty.views.api import api, ResolveView

routes = [
#    ((frontend, ''),
#        ('/', IndexView.as_view('index')),
#        ('/<short_code>', ShortLinkRedirectView.as_view('redir')),
#    ),
#    ((api, '/api'),
#        ('/resolve/<short_code>', ResolveView.as_view('resolve'))),
]

shorty/models.py
# -*- coding: utf-8 -*-

from datetime import datetime

from sqlalchemy.ext.declarative import declared_attr
from werkzeug.utils import cached_property

from shorty import db


class AutoInitModelMixin(object):
    """
    Mixin for populating models' columns automatically (no need to
    define an __init__ method) and set the default value if any.
    Also sets the model's id and __tablename__ automatically.
    """
    id = db.Column(db.Integer, primary_key=True)

    # use the lowercased class name as the __tablename__
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

    def __init__(self, *args, **kwargs):
        for attr in (a for a in dir(self) if not a.startswith('_')):
            attr_obj = getattr(self, attr)
            if isinstance(attr_obj, db.Column):
                if attr in kwargs:
                    setattr(self, attr, kwargs[attr])
                else:
                    if hasattr(attr_obj, 'default'):
                        if callable(attr_obj.default):
                            setattr(self, attr, attr_obj.default())
                        else:
                            setattr(self, attr, attr_obj.default)


class ShortURL(db.Model, AutoInitModelMixin):
    long_url = db.Column(db.String(255), unique=True)
    slug = db.Column(db.String(30), unique=True)
    created = db.Column(db.DateTime, default=datetime.now)
    clicks = db.relationship("Click")

    def __repr__(self):
        return "<ShortURL: '%s'>" % self.long_url


class Click(db.Model, AutoInitModelMixin):
    url_id = db.Column(db.Integer, db.ForeignKey('shorturl.id'))
    user_agent = db.Column(db.String(255), default='Unknown')
    time = db.Column(db.DateTime, default=datetime.now)
    #TODO: locate originating country/city
    #TODO: parse the user-agent to extract OS/browser_name/browser_version

    @cached_property
    def url(self):
        return ShortURL.query.filter_by(id=self.url_id).one()

    def __repr__(self):
        return "<Click on '%s'>" % self.url.long_url

shorty/core/forms/validators.py
# -*- coding: utf-8 -*-
#    This file is part of Shorty.
#
#    Shorty is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Shorty is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.

from flask.ext.wtf import ValidationError

import re


class StrongPassword(object):
    _re_lower = re.compile(r'[a-z]')
    _re_upper = re.compile(r'[A-Z]')
    _re_digit = re.compile(r'\d')
    _re_special = re.compile(r'[^a-zA-Z0-9]')

    def __init__(self,
                 min_length=12,
                 lowercase=True,
                 uppercase=True,
                 digit=True,
                 special=False):
        self.min_length = min_length
        self.lowercase = lowercase
        self.uppercase = uppercase
        self.digit = digit
        self.special = special

    def __call__(self, form, field):
        if len(field.data) < self.min_length:
            raise ValidationError('Must be at least %d characters long' % self.min_length)
        if self.lowercase and self._re_lower.search(field.data) is None:
            raise ValidationError('Must contain at least 1 lowercase character')
        if self.uppercase and self._re_upper.search(field.data) is None:
            raise ValidationError('Must contain at least 1 uppercase character')
        if self.digit and self._re_digit.search(field.data) is None:
            raise ValidationError('Must contain at least 1 digit')
        if self.special and self._re_special.search(field.data) is None:
            raise ValidationError('Must contain at least 1 special character')

shorty/core/forms/widgets.py
# -*- coding: utf-8 -*-
#    This file is part of Shorty.
#
#    Shorty is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Shorty is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.

from flask.ext.wtf import widgets


class ButtonWidget(object):
    def __call__(self, field, **kwargs):
        return widgets.HTMLString(u'<button %s>%s</button>' % (
            widgets.html_params(**kwargs),
            field.label.text))

shorty/forms.py
# -*- coding: utf-8 -*-

import re
from flask.ext.wtf import Form, TextField, TextInput, SubmitField
from flask.ext.wtf import Required, Optional, Length, URL, Regexp

from shorty.core.forms.widgets import XXLargeTextInput

RE_SLUG = re.compile(r'^[-\w]+$')

class URLForm(Form):
    url = TextField('URL', [Required(), Length(max=255), URL()], widget=XXLargeTextInput())
    slug = TextField('Slug', [Optional(), Length(max=30), Regexp(RE_SLUG)], widget=TextInput())
    submit = SubmitField('shorten')

shorty/views/api.py
# -*- coding: utf-8 -*-
#    This file is part of Shorty.
#
#    Shorty is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Shorty is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.

from flask import *
from flask.views import MethodView
from shorty.core.shortener import UrlEncoder, EncoderError
from shorty.models import ShortURL

api = Blueprint('api', __name__)


class ResolveView(MethodView):
    def get(self, short_code):
        try:
            url_code = short_code.split('/')[-1] if ('/' in short_code) else short_code
            url_id = UrlEncoder().decode_id(url_code)
            url_obj = ShortURL.query.get(url_id)
            ret = { 'success': { "url": url_obj.long_url } }
        except EncoderError:
            ret = { 'errors':  ['Unknow short URL'] }
        return jsonify(ret)
api.add_url_rule('/resolve/<short_code>', view_func=ResolveView.as_view('resolve'))

shorty/views/frontend.py
# -*- coding: utf-8 -*-

from flask import *
from flask.views import MethodView, View

from shorty.core.shortener import shorten_url, expand_url, expand_slug, EncoderError
from shorty.forms import URLForm

frontend = Blueprint('frontend', __name__)


class IndexView(MethodView):
    template = 'index.html'

    def get(self):
        form = URLForm()
        return render_template(self.template,
                               form=form)

    def post(self):
        form = URLForm()
        if not form.validate_on_submit():
            return render_template(self.template,
                                   form=form)
        short_code = shorten_url(form.data['url'], form.data.get('slug', ''))
        short_url = '%s/%s%s' % (current_app.config['BASE_URL'], current_app.config['PREFIX'], short_code)
        return render_template(self.template,
                               form=form,
                               short_url=short_url)


class ShortLinkRedirectView(View):
    methods = ['GET']

    def dispatch_request(self, short_code):
        if short_code.startswith(current_app.config['PREFIX']):
            try:
                long_url = expand_url(short_code[len(current_app.config['PREFIX']):])
                return redirect(long_url)
            except EncoderError:
                flash('Unknown short URL', category='error')
                return redirect(url_for('frontend.index'))
        else:
            long_url = expand_slug(short_code)
            return redirect(long_url)

shorty/views/users.py
# -*- coding: utf-8 -*-
#    This file is part of Shorty.
#
#    Shorty is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Shorty is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.

from flask import *
from flask.ext.login import current_user, login_user, logout_user
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from werkzeug.security import generate_password_hash, check_password_hash

from shorty import db
from shorty.models import User
from shorty.core.forms import RegisterForm, LoginForm
from shorty.core.log import getLogger

users = Blueprint('users', __name__)
logger = getLogger(__name__)

PASSWORD_REQUIREMENTS_STR = """
<ul>
<li>At least 12 characters long</li>
<li>Contains at least 1 uppercase letter</li>
<li>Contains at least 1 lowercase letter</li>
<li>Contains at least 1 digit</li>
</ul>
"""


@users.route('/login', methods=('GET', 'POST'))
def login():
    tpl = 'users/login.html'
    form = LoginForm()

    if request.method == 'POST':
        login_success = True
        if not form.validate_on_submit():
            return render_template(tpl,
                login_form=form
            )
        username = form.data['username']
        try:
            user = User.query.filter_by(name=username).one()
        except NoResultFound:
            logger.warning("login attempt with unknown username '%s'" % username)
            flash("Invalid username or password", category='error')
            login_success = False
        else:
            if not check_password_hash(user.password, form.data['password']):
                logger.warning("login failed for username '%s'" % username)
                flash("Invalid username or password", category='error')
                login_success = False
            else:
                login_user(user)
                logger.info("successful login for '%s'" % username)
                flash("Log in successful", category='success')
        if login_success:
            return redirect(url_for('frontend.index'))
        return render_template(tpl,
            login_form=form
        )

    return render_template(tpl,
        login_form=form,
    )

@users.route('/register', methods=('GET', 'POST'))
def register():
    tpl = 'users/register.html'
    form = RegisterForm()

    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template(tpl,
                reg_form=form
            )
        username = form.data['username']
        user_obj = User(
            name=username,
            email=form.data['email'],
            password=generate_password_hash(form.data['password']),
            active=True
        )
        db.session.add(user_obj)
        try:
            db.session.commit()
        except IntegrityError:
            logger.info("failed registration attempt for '%s'" % username)
            flash('An user already exists with given details', category='error')
        else:
            logger.info("user '%s' successfully registered" % username)
            flash('Registration complete. You can sign in.', category='info')
        return redirect(url_for('frontend.index'))

    return render_template(tpl,
        reg_form=form,
        password_requirements=PASSWORD_REQUIREMENTS_STR
    )

@users.route('/logout', methods=('POST',))
def logout():
    if current_user.is_authenticated():
        logout_user()
        logger.info("user '%s' logged out" % current_user.username)
        flash("Successfully logged out", category='success')
    else:
        logger.info("logout attempt from unauthenticated user")
        flash("You're not authenticated", category='error')
    return ''

@users.route('/profile')
def profile():
    return render_template('users/profile.html',
        current_user=current_user
    )

@users.route('/links')
def links():
    links = current_user.shorturls.all()
    return render_template('users/links.html',
        links=links
    )

shorty/templates/base.html
{#
    This file is part of Shorty.

    Shorty is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Shorty is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.
#}

<!DOCTYPE HTML>
<html>
<head>
    <title>Shorty - {% block title %}Simply URL shortening...{% endblock %}</title>
    <!-- CSS -->
    {% assets "css" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}" />#}
{#    <link rel="stylesheet" type="text/css" href="{{ BOOTSTRAP }}/css/bootstrap.min.responsive" />#}
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shorty.css') }}" />#}
    {% block extra_css %}{% endblock %}
    <!-- END CSS -->
</head>

<body>
{% include 'header.html' %}
<div class="container">
    <!-- ForkMe -->
    <a href="https://github.com/mattoufoutu/shorty" class="github-ribbon" target="_blank">
        <img style="position: absolute; top: 40px; right: 0; border: 0;"
             src="https://a248.e.akamai.net/assets.github.com/img/abad93f42020b733148435e2cd92ce15c542d320/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67"
             alt="Fork me on GitHub">
    </a>
    <!-- END ForkMe -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} fade in" data-dismiss='alert'>
                    <a class="close" data-dismiss="alert" href="#">&times;</a>
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block body %}{% endblock %}
    <footer>
        {% include 'footer.html' %}
    </footer>
</div>
</body>
<!-- Javascript -->
{% block js %}
    {% assets "js" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock js %}
<!-- END Javascript -->
</html>

shorty/templates/footer.html
{#
    This file is part of Shorty.

    Shorty is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Shorty is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.
#}

<p>&copy; <a href="mailto:mattoufootu@gmail.com">MatToufoutu</a> 2011
 | Licensed under the GNU General Public License v3</p>

shorty/templates/header.html
{#
    This file is part of Shorty.

    Shorty is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Shorty is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.
#}

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{{ url_for('frontend.index') }}">
                <i class="icon-home icon-white"></i>
            </a>
            {% if current_user.is_authenticated() %}
                <ul class="nav pull-right">
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.name }}<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('users.links') }}"><i class="icon-th-list"></i> My links</a></li>
                            <li><a href="{{ url_for('users.profile') }}"><i class="icon-user"></i> Profile</a></li>
                            <li class="divider"></li>
                            <li><a href="#" class="logout_link"><i class="icon-off"></i> Sign Out</a></li>
                        </ul>
                    </li>
                    <li class="divider-vertical"></li>
                </ul>
            {% else %}
                <ul class="nav pull-right">
                    <li class="divider-vertical"></li>
                    <li><a href="{{ url_for('users.login') }}">Sign In</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="{{ url_for('users.register') }}">Register</a></li>
                    <li class="divider-vertical"></li>
                </ul>
            {% endif %}
        </div>
    </div>
</div>

shorty/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macros %}
{% block body %}

<div class="row">
    <div class="span14">
        <form method="POST" action="{{ url_for('frontend.index') }}">
            <fieldset>
                {{ macros.render_field(form.url, with_label=False) }}
                <br />
                {{ macros.render_field(form.slug, with_label=False) }}
                <br />
                <input class="btn primary" type="submit" value="Make It Short !">
                {{ form.hidden_tag() }}
            </fieldset>
        </form>
    </div>
</div>

<div class="row">
    <div class="span14">
    {% if short_url %}
        <h1><a href="{{ short_url }}" class="shorturl">{{ short_url }}</a></h1>
    {% endif %}
    </div>
</div>

{% endblock %}

shorty/templates/macros.html
{#
    This file is part of Shorty.

    Shorty is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Shorty is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.
#}

{% macro render_field(field, with_label=True) %}
    <div class="control-group{% if field.errors %} error{% endif %}">
        {% if field.errors %}
        <div class="alert alert-block alert-error">
            <p><strong>{{ field.name|capitalize }}:</strong></p>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% if with_label %}{{ field.label }} {% endif %}{{ field(**kwargs) }}
    </div><br />
{% endmacro %}

shorty/templates/register.html
{#
    This file is part of Shorty.

    Shorty is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Shorty is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Shorty.  If not, see <http://www.gnu.org/licenses/>.
#}

{% extends 'base.html' %}
{% import 'macros.html' as macros %}

{% block body %}
<div class="row">
    <div class="span14">
        <br />
        <h4><em>Please enter your details to register.</em></h4>
        <br />
    </div>
</div>
<div class="row">
    <div class="span14">
        <form method="POST" action="{{ url_for('users.register') }}">
            <fieldset>
                {{ macros.render_field(reg_form.username, with_label=False, placeholder=reg_form.username.label.text, class="xlarge") }}
                {{ macros.render_field(reg_form.email, with_label=False, placeholder=reg_form.email.label.text, class="xlarge") }}
                {{ macros.render_field(reg_form.password, with_label=False, placeholder=reg_form.password.label.text, class="xlarge") }}
                {{ macros.render_field(reg_form.confirm, with_label=False, placeholder=reg_form.confirm.label.text, class="xlarge") }}
                {{ macros.render_field(reg_form.submit, with_label=False, class="btn primary", value=reg_form.submit.label.text) }}
                {{ reg_form.hidden_tag() }}
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}